### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by indilo53** [davedumas0/fiveM-interior-Menu#1]
Hello, I learned a lot from your script, but how do you find the list of props for a given interior ? I tried to find them in OpenIV but no success.

**Comment by davedumas0** [comment]
i just searched the decompiled scripts for "Enable_Interior_Prop" and look for what interior that certain prop is getting enabled in 
![untitled90](https://user-images.githubusercontent.com/20492304/30435904-c215e190-991f-11e7-8343-c799df1b5102.png)

**Comment by davedumas0** [comment]
like this one 
`interior::_enable_interior_prop(iVar100, &(Var3.f_8[0 /*8*/]));`
i would look for "iVar100" to get the interior and "Var3.f_8" at index 0 for the prop to be enabled
so if i look for the interior(iVar100) i find this 
`iVar100 = interior::get_interior_at_coords_with_type(Var3, &(Var3.f_42));`
so then i gotta look for "Var3.f_42" so i do another search but this time im looking for "f_42" in the same script
i find multiple things like "V_Michael", and "V_Michael_Garage" these are the interiors you still need to "track" down the interior props

**Comment by davedumas0** [comment]
does that help?

**Comment by indilo53** [comment]
Yes thank you ! Sorry for the late reply
